version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        depends_on:
            - php
    php:
        build: ./images/php
        user: "${USER_UID}:${USER_GID}"
        links:
            - mysql
        volumes:
            - ./www:/var/www
    mysql:
        platform: linux/x86_64
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password!@#$%

